name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Download JUnit 5
        run: |
          mkdir -p libs
          curl -L -o libs/junit-platform-console-standalone-1.8.1.jar \
            https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.1/junit-platform-console-standalone-1.8.1.jar

      - name: Compile Java code
        run: |
          mkdir -p out
          javac -d out/ -cp "libs/junit-platform-console-standalone-1.8.1.jar" "PasswordGenerator/src/**/*.java"

      - name: Run tests
        run: |
          java -jar libs/junit-platform-console-standalone-1.8.1.jar \
          --class-path out/ \
          --scan-class-path

      - name: Package runnable JAR
        run: |
          jar cfe PasswordGenerator.jar Main -C out/ .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: password-generator
          path: PasswordGenerator.jar
